# To run the install only on the http package: 
# ansible-navigator run -m stdout httpbytags.yml -t i-httpd
# To list all tags in a playbook:
# ansible-navigator run -m stdout httpbytags.yml --list-tags
# To skip a tag:
# ansible-navigator run -m stdout httpbytags.yml --skip-tags i-httpd

---
- name: Setup Apache server
  hosts: localhost
  tasks:
  - name: Install httpd
    yum:
     name: httpd
     state: present
    tags: i-httpd

  - name: Start httpd
    service:
     name: httpd
     state: started
    tags: s-httpd  
