---
- name: Copy file to remote clients
  hosts: all
  vars:
   srcfile: /home/student/somefile
  tasks:
   
  - name: Copying file
    become: true
    copy:
     src: “{{ srcfile }}”
     dest: /tmp
     owner: student
     group: student
     mode: 0644
