---
- name: Run stat module
  hosts: localhost

  tasks:
          - name: Check file status and attributes
            stat:                 # stat module
               path: /etc/hosts   # File path/location
            register: fs  # Register or output to fs container

          - name: Show values
            debug:
                    msg: File attributes {{ fs }}  # Print what's inside the fs container
