---
- name: command module demo
  hosts: all
  
  tasks:
    - name: check uptime
      ansible.builtin.command:
      register: command_output

    - name: command output
      ansible.builtin.debug:
        var: command_output.stdout_lines
