---
- name: Create a cron job
  hosts: all

  tasks:
    - name: Schedule cron:
      cron:
	   name: This job is scheduled by Ansible
	   minute: “0”
	   hour: “10”
	   day: “*”
	   month: “*”
	   weekday: “4“                           # The day of the week we want it to run is on Thursday
	   user: root
	   job: “/home/student/cfile.sh”
