---
- name: firewalld module demo
  hosts: all

  tasks:

    - name: nginx installed
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: firewalld rules
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - http
        - https
