# NOTE: Ansible does not allow us to pass a cleartext password through the user module
# the "newpassword" below is only a variable name.  You can use anything there.

# To run the playbook, you must specify the --extra-vars:
# ansible-playbook changepass.yml --extra-vars newpassword=abc123

---
- name: Add or update user password
  hosts: all
  
  tasks:
  - name: Change “george” password
    user:
      name: george
      update_password: always
      password: "{{ newpassword|password_hash('sha512’) }}”
