---
- name: delete file(s) in a dir demo
  hosts: all
  vars:
    mypath: "/home/student/example"

  tasks:
    - name: Collect files
      ansible.builtin.find:
        paths: "{{ mypath }}"
        hidden: true
        recurse: true
        file_type: any
      register: collected_files

    - name: Remove collected files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ collected_files }}"
