---
- name: File module symlink demo
  hosts: all
  become: true
  vars:
    # Define absolute paths
    mylink: "/home/{{ ansible_user }}/example"
    mysrc: "/etc/hosts"

  tasks:
    - name: Creating a symlink
      ansible.builtin.file:
        src: "{{ mysrc }}"
        dest: "{{ mylink }}"
        state: link
